import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import OBR from"@owlbear-rodeo/sdk";
import{getSelectedRyder,saveRyder}from"./storage";
import{costAmount,overheatResult,resolveAttack,rollDie,structureResult}from"./rules";
import{CHANNEL,crypto,defaultRyder,fixed,type ActionDef,type CombatMessage,type ReactionDef,type ResourceCost,type RyderData,type Weapon}from"./types";
import"./style.css";

function Num({value,onChange}:{value:number;onChange:(v:number)=>void}){return <input type="number" value={Number.isFinite(value)?value:0} onChange={e=>onChange(Number(e.target.value))}/>}
function CostEditor({cost,onChange}:{cost:ResourceCost;onChange:(c:ResourceCost)=>void}){return <span className="cost"><select value={cost.mode} onChange={e=>onChange({mode:e.target.value as ResourceCost["mode"],value:cost.value})}><option value="fixed">Fixed</option><option value="percent">%</option></select><Num value={cost.value} onChange={v=>onChange({...cost,value:v})}/></span>}
function playSound(url:string){if(!url)return;try{const audio=new Audio(url);audio.play().catch(()=>{});}catch{}}
async function requestReaction(targetId:string,attackId:string){
  await OBR.broadcast.sendMessage(CHANNEL,{type:"reaction_request",id:attackId,data:{targetId}},{destination:"ALL"});
  return await new Promise<{evasionBonus:number}|null>(resolve=>{
    let done=false;
    const finish=(v:{evasionBonus:number}|null)=>{if(done)return;done=true;off();resolve(v);};
    const off=OBR.broadcast.onMessage(CHANNEL,e=>{const m=e.data as CombatMessage;if(m.type!=="reaction_response"||m.id!==attackId)return;const data=m.data as any;finish({evasionBonus:Number(data?.evasionBonus||0)});});
    window.setTimeout(()=>finish(null),5000);
  });
}
function App(){
 const[ready,setReady]=useState(false),[error,setError]=useState(""),[sel,setSel]=useState<any>(null),[tab,setTab]=useState("stats"),[msg,setMsg]=useState(""),[lockedId,setLockedId]=useState<string|null>(null),[targetInfo,setTargetInfo]=useState(""),[log,setLog]=useState<string[]>([]),[pending,setPending]=useState<any>(null);
 const refresh=async()=>{try{if(!lockedId)setSel(await getSelectedRyder());setError("");}catch(e){setError(e instanceof Error?e.message:String(e));}};
 const announce=async(text:string,color?:string)=>{setLog(x=>[text,...x].slice(0,20));setMsg(text);await OBR.broadcast.sendMessage(CHANNEL,{type:"result",id:crypto(),text,color},{destination:"ALL"});try{OBR.notification.show(text);}catch{}}
 useEffect(()=>{let off=()=>{};OBR.onReady(async()=>{setReady(true);await refresh();off=OBR.broadcast.onMessage(CHANNEL,e=>{const m=e.data as CombatMessage;if(m.type==="result"&&m.text){setLog(x=>[m.text!,...x].slice(0,20));setMsg(m.text!);}if(m.type==="reaction_request"){const data=m.data as any;if(data?.targetId===sel?.item?.id)setPending(m);}});});return()=>off();},[lockedId,sel?.item?.id]);
 useEffect(()=>{void (async()=>{if(sel?.data?.color==="#ffffff"){const playerColor=await OBR.player.getColor(); if(playerColor) save({color:playerColor});}})();},[sel?.item?.id]);
 if(!ready)return <main><h2>PWB Ryder Combat</h2><p>Connecting to Owlbear Rodeo…</p></main>;
 if(error)return <main><h2>PWB Ryder Combat</h2><section><b>Extension error</b><p>{error}</p><button onClick={()=>void refresh()}>RETRY</button></section></main>;
 if(!sel)return <main><h2>PWB Ryder Combat</h2><p>Select a Character token.</p></main>;
 const{item}=sel;const d=sel.data as RyderData;
 const save=(patch:Partial<RyderData>)=>{const nd={...d,...patch};setSel({item,data:nd});void saveRyder(item.id,nd)};
 const n=(k:keyof RyderData)=><Num value={Number(d[k])} onChange={v=>save({[k]:v} as any)}/>;
 const startTurn=()=>{const energy=Math.min(d.maxEnergy+d.energyBonus,d.energy+d.energyRefresh);const heat=Math.max(0,d.heat-(d.heatVent+d.heatVentBonus));save({energy,heat});setMsg("Turn started: Energy refreshed and Heat vented.");};
 const addWeapon=()=>save({weapons:[...d.weapons,{id:crypto(),name:"New Weapon",ammo:10,maxAmmo:10,ammoCost:fixed(1),energyCost:fixed(0),heatCost:fixed(0),damage:"1d10",toHit:0,range:1200,fireRate:1,critical:20,effect:"",attackType:"ranged",status:"",soundUrl:""} as any]});
 const target=async()=>{if(!lockedId){setTargetInfo("Lock the attacker first.");return null;}const ids=await OBR.player.getSelection();const all=await OBR.scene.items.getItems(ids||[]);const t=all.find(x=>x.id!==lockedId&&x.layer==="CHARACTER");if(!t){setTargetInfo("Select a target token after locking the attacker.");return null;}const td=({...defaultRyder(),...((t.metadata?.["com.pwb.ryder-combat/data"] as RyderData)||{})}) as RyderData;const attacker=(await OBR.scene.items.getItems([lockedId])).find(x=>x.layer==="CHARACTER");if(!attacker)return null;let distance=0;try{distance=await OBR.scene.grid.getDistance((attacker as any).position,(t as any).position);}catch{const a=(attacker as any).position||{x:0,y:0},b=(t as any).position||{x:0,y:0};distance=Math.hypot(a.x-b.x,a.y-b.y);}const sensor=(d.sensor||0)+(d.sensorBonus||0);if(distance>sensor){setTargetInfo(`TARGET OUTSIDE SENSOR RANGE — ${Math.round(distance)} / ${sensor}`);return null;}setTargetInfo(`${t.name||"Target"} — ${Math.round(distance)} range units`);return{item:t,data:td,distance};};
 const attack=async(w:Weapon)=>{const picked=await target();if(!picked)return;const{item:t,data:td,distance}=picked;const range=w.range||0;if(distance>range){await announce(`${d.name||item.name||"Ryder"}: ${w.name} — OUT OF RANGE (${Math.round(distance)} / ${range}).`,d.color);return;}const ammoCost=costAmount(w.ammoCost,w.maxAmmo??w.ammo);const energyCost=costAmount(w.energyCost,d.maxEnergy);const heatCost=costAmount(w.heatCost,d.heatCapacity);const count=Math.max(1,Math.floor(w.fireRate));if(w.ammo<ammoCost*count){await announce(`${d.name}: ${w.name} — NOT ENOUGH AMMO.`,d.color);return;}if(d.energy<energyCost*count){await announce(`${d.name}: ${w.name} — NOT ENOUGH ENERGY.`,d.color);return;}if(w.attackType==="melee"&&distance>w.range){await announce(`${d.name}: ${w.name} — MELEE RANGE EXCEEDED.`,d.color);return;}const reactionId=crypto();const reaction=await requestReaction(t.id,reactionId);const reactionEvasion=reaction?.evasionBonus||0;let hits=0,crit=0,total=0,cover=0;const details:string[]=[];for(let i=0;i<count;i++){const r=resolveAttack(w.toHit+d.attackBonus,(td.evasion||0)+(td.evasionBonus||0)+reactionEvasion,w.damage,(td.armor||0)+(td.armorBonus||0),td.cover,w.critical,d.damageBonus);if(r.hit)hits++;if(r.critical)crit++;if(r.hitCover)cover++;total+=r.finalDamage;details.push(`d20 ${r.roll}+${w.toHit+d.attackBonus}=${r.total}${r.critical?" CRIT":""}${r.hitCover?" COVER":r.hit?` ${r.finalDamage} dmg`:" MISS"}`);}
 let targetStructure="",targetOverheat="";
 await OBR.scene.items.updateItems([t.id],xs=>{for(const x of xs){const cur=({...defaultRyder(),...((x.metadata?.["com.pwb.ryder-combat/data"] as RyderData)||{})}) as RyderData;cur.hp=Math.max(0,cur.hp-total);if(cur.hp<=0){cur.disabled=true;targetStructure=structureResult();}if(crit>0){targetStructure=structureResult();targetOverheat=overheatResult();if(targetStructure==="Critical Damage")cur.disabled=true;cur.unstable=true;if(targetOverheat==="Reactor Meltdown")cur.meltdown=true;if(targetOverheat==="Reactor Overheat")cur.energy=Math.floor(cur.maxEnergy/2);}if(w.status&&hits>0&&!cur.statuses.includes(w.status))cur.statuses=[...cur.statuses,w.status];x.metadata["com.pwb.ryder-combat/data"]=cur;}});
 const nw={...w,ammo:w.ammo-ammoCost*count};const newHeat=d.heat+heatCost*count;save({energy:Math.max(0,d.energy-energyCost*count),heat:newHeat,weapons:d.weapons.map(x=>x.id===w.id?nw:x)});playSound(w.soundUrl);let extra=reaction?` Defender reaction +${reactionEvasion} Evasion.`:"";if(targetStructure)extra+=` Structure: ${targetStructure}.`;if(targetOverheat)extra+=` Overheat: ${targetOverheat}.`;if(newHeat>d.heatCapacity+d.heatCapacityBonus){const oh=overheatResult();extra+=` Attacker ${oh}.`;if(oh==="Reactor Meltdown")save({meltdown:true});else if(oh==="Reactor Overheat")save({energy:Math.floor(d.maxEnergy/2)});}if(w.status&&hits>0)extra+=` Status: ${w.status}.`;await announce(`${d.name||item.name||"Ryder"} fires ${w.name} at ${t.name||"Target"} — ${hits}/${count} hits, ${crit} critical, ${cover} cover, ${total} damage.${extra}`,d.color);setTargetInfo(details.join(" | "));};
 const updateW=(idx:number,p:Partial<Weapon>)=>save({weapons:d.weapons.map((w,i)=>i===idx?{...w,...p}:w)});
 const addAction=()=>save({actions:[...d.actions,{id:crypto(),name:"New Action",energyCost:fixed(0),heatCost:fixed(0),effect:"",soundUrl:""}]});
 const useAction=async(a:ActionDef)=>{const ec=costAmount(a.energyCost,d.maxEnergy),hc=costAmount(a.heatCost,d.heatCapacity);if(d.energy<ec){setMsg("Not enough Energy.");return;}save({energy:d.energy-ec,heat:d.heat+hc});playSound(a.soundUrl);await announce(`${d.name||item.name||"Ryder"} activates ${a.name}.${a.effect?` ${a.effect}`:""}`,d.color);};
 const addReaction=()=>save({reactions:[...d.reactions,{id:crypto(),name:"New Reaction",trigger:"before_attack",energyCost:fixed(0),heatCost:fixed(0),evasionBonus:0,effect:"",enabled:true}]});
 const useReaction=async(r:ReactionDef)=>{const ec=costAmount(r.energyCost,d.maxEnergy),hc=costAmount(r.heatCost,d.heatCapacity);if(d.energy<ec){setMsg("Not enough Energy for reaction.");return;}save({energy:d.energy-ec,heat:d.heat+hc});if(pending){await OBR.broadcast.sendMessage(CHANNEL,{type:"reaction_response",id:pending.id,data:{evasionBonus:r.evasionBonus}},{destination:"ALL"});await announce(`${d.name||item.name||"Ryder"} uses reaction ${r.name}.${r.effect?` ${r.effect}`:""}`,d.color);}else{await announce(`${d.name||item.name||"Ryder"} uses reaction ${r.name}.${r.effect?` ${r.effect}`:""}`,d.color);}setPending(null);};
 return <main><h2 style={{borderLeft:`5px solid ${d.color}`,paddingLeft:8}}>{d.name||item.name||"Ryder"}</h2><section><label>Ryder Name<input value={d.name} onChange={e=>save({name:e.target.value})}/></label><label>Ryder Color<input type="color" value={d.color} onChange={e=>save({color:e.target.value})}/></label><button onClick={()=>void (async()=>save({color:await OBR.player.getColor()}))()}>USE MY OWLBEAR COLOR</button></section><button onClick={()=>{setLockedId(lockedId?null:item.id);setMsg(lockedId?"Attacker unlocked.":"Attacker locked. Select the target token now.")}}>{lockedId?"UNLOCK ATTACKER":"LOCK ATTACKER"}</button><nav>{["stats","weapons","actions","reactions","systems"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</nav>
 {tab==="stats"&&<><section><h3>Core</h3><div className="grid">{[["HP","hp"],["Max HP","maxHp"],["HP Bonus","hpBonus"],["Armor","armor"],["Armor Bonus","armorBonus"],["Energy","energy"],["Max Energy","maxEnergy"],["Energy Bonus","energyBonus"],["Heat","heat"],["Heat Capacity","heatCapacity"],["Heat Cap Bonus","heatCapacityBonus"],["Heat Vent","heatVent"],["Heat Vent Bonus","heatVentBonus"],["Evasion","evasion"],["Evasion Bonus","evasionBonus"],["Sensor","sensor"],["Sensor Bonus","sensorBonus"],["Attack Bonus","attackBonus"],["Damage Bonus","damageBonus"],["Tech Attack Bonus","techAttackBonus"]].map(([l,k])=><label key={k}>{l}{n(k as keyof RyderData)}</label>)}</div></section><section><h3>Turn / Team</h3><label>Team<input value={d.team} onChange={e=>save({team:e.target.value})}/></label><label>Energy Refresh{n("energyRefresh")}</label><label>Heat Vent at Start{n("heatVentRefresh")}</label><button className="primary" onClick={startTurn}>START TURN</button></section><section><h3>Cover</h3><select value={d.cover} onChange={e=>save({cover:e.target.value as any})}><option value="none">None</option><option value="light">Light</option><option value="medium">Medium</option><option value="hard">Hard</option><option value="full">Full</option></select><p>Statuses: {d.statuses.length?d.statuses.join(", "):"None"}</p></section></>}
 {tab==="weapons"&&<section><button onClick={addWeapon}>+ Weapon</button>{d.weapons.map((w,i)=><article key={w.id}><input className="wide" value={w.name} onChange={e=>updateW(i,{name:e.target.value})}/><div className="grid"><label>Ammo<Num value={w.ammo} onChange={v=>updateW(i,{ammo:v})}/></label><label>Max Ammo<Num value={(w as any).maxAmmo??w.ammo} onChange={v=>updateW(i,{maxAmmo:v} as any)}/></label><label>Ammo Cost<CostEditor cost={w.ammoCost} onChange={v=>updateW(i,{ammoCost:v})}/></label><label>Energy Cost<CostEditor cost={w.energyCost} onChange={v=>updateW(i,{energyCost:v})}/></label><label>Heat Cost<CostEditor cost={w.heatCost} onChange={v=>updateW(i,{heatCost:v})}/></label><label>To Hit<Num value={w.toHit} onChange={v=>updateW(i,{toHit:v})}/></label><label>Range<Num value={w.range} onChange={v=>updateW(i,{range:v})}/></label><label>Fire Rate<Num value={w.fireRate} onChange={v=>updateW(i,{fireRate:v})}/></label><label>Critical<Num value={w.critical} onChange={v=>updateW(i,{critical:v})}/></label></div><label>Attack Type<select value={w.attackType} onChange={e=>updateW(i,{attackType:e.target.value as any})}><option value="ranged">Ranged</option><option value="melee">Melee</option></select></label><label>Damage<input value={w.damage} onChange={e=>updateW(i,{damage:e.target.value})}/></label><label>Status on Hit<input value={w.status} onChange={e=>updateW(i,{status:e.target.value})}/></label><label>Sound URL<input value={w.soundUrl} onChange={e=>updateW(i,{soundUrl:e.target.value})}/></label><label>Effect<textarea value={w.effect} onChange={e=>updateW(i,{effect:e.target.value})}/></label><button className="primary" onClick={()=>void attack(w)}>ATTACK TARGET</button></article>)}</section>}
 {tab==="actions"&&<section><button onClick={addAction}>+ Custom Action</button>{d.actions.map((a,i)=><article key={a.id}><input className="wide" value={a.name} onChange={e=>save({actions:d.actions.map((x,j)=>j===i?{...x,name:e.target.value}:x)})}/><label>Energy Cost<CostEditor cost={a.energyCost} onChange={v=>save({actions:d.actions.map((x,j)=>j===i?{...x,energyCost:v}:x)})}/></label><label>Heat Cost<CostEditor cost={a.heatCost} onChange={v=>save({actions:d.actions.map((x,j)=>j===i?{...x,heatCost:v}:x)})}/></label><label>Sound URL<input value={a.soundUrl} onChange={e=>save({actions:d.actions.map((x,j)=>j===i?{...x,soundUrl:e.target.value}:x)})}/></label><textarea value={a.effect} onChange={e=>save({actions:d.actions.map((x,j)=>j===i?{...x,effect:e.target.value}:x)})}/><button onClick={()=>void useAction(a)}>USE ACTION</button></article>)}</section>}
 {tab==="reactions"&&<section><p>Reactions are prepared responses. This first pass provides a shared reaction button and public announcement; a full timed reaction window will be added separately.</p><button onClick={addReaction}>+ Reaction</button>{d.reactions.map((r,i)=><article key={r.id}><input className="wide" value={r.name} onChange={e=>save({reactions:d.reactions.map((x,j)=>j===i?{...x,name:e.target.value}:x)})}/><label>Trigger<select value={r.trigger} onChange={e=>save({reactions:d.reactions.map((x,j)=>j===i?{...x,trigger:e.target.value as any}:x)})}><option value="before_attack">Before Attack</option><option value="after_hit">After Hit</option></select></label><label>Energy Cost<CostEditor cost={r.energyCost} onChange={v=>save({reactions:d.reactions.map((x,j)=>j===i?{...x,energyCost:v}:x)})}/></label><label>Heat Cost<CostEditor cost={r.heatCost} onChange={v=>save({reactions:d.reactions.map((x,j)=>j===i?{...x,heatCost:v}:x)})}/></label><label>Evasion Bonus<Num value={r.evasionBonus} onChange={v=>save({reactions:d.reactions.map((x,j)=>j===i?{...x,evasionBonus:v}:x)})}/></label><textarea value={r.effect} onChange={e=>save({reactions:d.reactions.map((x,j)=>j===i?{...x,effect:e.target.value}:x)})}/><button onClick={()=>void useReaction(r)}>USE REACTION</button></article>)}{pending&&<section className="reaction"><b>REACTION REQUEST</b><p>An incoming attack is requesting a reaction.</p><button onClick={()=>{const r=d.reactions.find(x=>x.enabled&&x.trigger==="before_attack");if(r)void useReaction(r);else setPending(null)}}>USE READY REACTION</button><button onClick={()=>setPending(null)}>DECLINE</button></section>}</section>}
 {tab==="systems"&&<section><h3>Structure</h3><button onClick={()=>setMsg(`Structure Check: ${structureResult()}`)}>STRUCTURE CHECK</button><h3>Overheat</h3><button onClick={()=>{const r=rollDie(6);if(r>=5)setMsg("Reactor Stress");else if(r>=2){save({energy:Math.floor(d.maxEnergy/2)});setMsg("Reactor Overheat: Energy reduced to 50%.");}else{save({meltdown:true});setMsg("REACTOR MELTDOWN");}}}>OVERHEAT CHECK</button><p>Disabled: {String(d.disabled)}</p><p>Meltdown: {String(d.meltdown)}</p><p>Unstable: {String(d.unstable)}</p><h3>Sensor / Target</h3><p>{targetInfo||"Select a target after locking the attacker."}</p><h3>Combat Log</h3>{log.slice(0,10).map((x,i)=><p key={i}>{x}</p>)}</section>}
 {msg&&<p className="msg" style={{borderColor:d.color}}>{msg}</p>}</main>;
}
createRoot(document.getElementById("root")!).render(<App/>);
