import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import OBR from"@owlbear-rodeo/sdk";
import{getRyderById,getRyders,getSelectedRyder,saveRyder}from"./storage";
import{costAmount,overheatResult,resolveAttack,rollDie,structureResult}from"./rules";
import{CHANNEL,crypto,defaultRyder,fixed,type ActionDef,type CombatMessage,type Cover,type PilotData,type ReactionDef,type ResourceCost,type RyderData,type RollMode,type TalentDef,type Weapon}from"./types";
import"./style.css";

const reactionWaiters=new Map<string,(value:any)=>void>();
const short=(n:number)=>Math.round(n).toLocaleString();
function Num({value,onChange}:{value:number;onChange:(v:number)=>void}){return <input type="number" value={Number.isFinite(value)?value:0} onChange={e=>onChange(Number(e.target.value))}/>}
function CostEditor({cost,onChange}:{cost:ResourceCost;onChange:(c:ResourceCost)=>void}){return <span className="cost"><select value={cost.mode} onChange={e=>onChange({mode:e.target.value as ResourceCost["mode"],value:cost.value})}><option value="fixed">Fixed</option><option value="percent">%</option></select><Num value={cost.value} onChange={v=>onChange({...cost,value:v})}/></span>}
function playSound(url:string){if(!url)return;try{const a=new Audio(url);void a.play().catch(()=>{});}catch{}}
async function playerId(){return OBR.player.id;}
async function playerName(){try{return await OBR.player.getName();}catch{return "Player";}}
async function playerColor(){try{return await OBR.player.getColor();}catch{return "#ffffff";}}
async function isGM(){try{return String(await (OBR.player as any).getRole?.()).toUpperCase()==="GM";}catch{return false;}}
async function distanceBetween(a:any,b:any){try{return await OBR.scene.grid.getDistance(a.position,b.position);}catch{const p=a.position||{x:0,y:0},q=b.position||{x:0,y:0};return Math.hypot(p.x-q.x,p.y-q.y);}}

function App(){
 const[ready,setReady]=useState(false),[error,setError]=useState(""),[attacker,setAttacker]=useState<any>(null),[lockedId,setLockedId]=useState(""),[selectedTarget,setSelectedTarget]=useState<any>(null),[tab,setTab]=useState("stats"),[message,setMessage]=useState(""),[log,setLog]=useState<{text:string;color?:string}[]>([]),[pending,setPending]=useState<any>(null),[sensorTargets,setSensorTargets]=useState<any[]>([]),[myId,setMyId]=useState(""),[myName,setMyName]=useState("");
 const refreshAttacker=async()=>{try{if(lockedId){const r=await getRyderById(lockedId);if(r)setAttacker(r);return;}const r=await getSelectedRyder();if(r)setAttacker(r);setError("");}catch(e){setError(e instanceof Error?e.message:String(e));}};
 const announce=async(text:string,color?:string)=>{const m:CombatMessage={type:"result",id:crypto(),text,color};await OBR.broadcast.sendMessage(CHANNEL,m,{destination:"ALL"});};
 const localResult=(text:string,color?:string)=>{setMessage(text);setLog(x=>[{text,color},...x].slice(0,30));try{OBR.notification.show(text);}catch{}};
 const loadSensor=async()=>{if(!lockedId||!attacker)return;const all=await getRyders();const out:any[]=[];for(const r of all){if(r.item.id===lockedId)continue;const dist=await distanceBetween(attacker.item,r.item);const range=(attacker.data.sensor||0)+(attacker.data.sensorBonus||0);if(dist<=range)out.push({...r,distance:dist});}out.sort((a,b)=>a.distance-b.distance);setSensorTargets(out);};
 const selectedIds=async()=>await OBR.player.getSelection();
 const chooseTarget=async(id:string)=>{const r=await getRyderById(id);if(!r)return;const dist=await distanceBetween(attacker.item,r.item);const sensor=(attacker.data.sensor||0)+(attacker.data.sensorBonus||0);if(dist>sensor){localResult(`TARGET OUTSIDE SENSOR RANGE — ${short(dist)} / ${short(sensor)} ft.`,attacker.data.color);return;}setSelectedTarget({...r,distance:dist});};
 const syncMapTarget=async()=>{if(!lockedId||!attacker)return;const ids=await selectedIds();if(!ids?.length)return;const all=await OBR.scene.items.getItems(ids);const t=all.find(x=>x.layer==="CHARACTER"&&x.id!==lockedId);if(t)await chooseTarget(t.id);};
 useEffect(()=>{let offPlayer=()=>{},offBroadcast=()=>{},offItems=()=>{};void OBR.onReady(async()=>{setReady(true);setMyId(await playerId());setMyName(await playerName());await refreshAttacker();offPlayer=OBR.player.onChange(()=>{if(!lockedId)void refreshAttacker();else void syncMapTarget();});offBroadcast=OBR.broadcast.onMessage(CHANNEL,e=>{const m=e.data as CombatMessage;if(m.type==="result"&&m.text)localResult(m.text,m.color);if(m.type==="reaction_response"){const f=reactionWaiters.get(m.id);if(f){reactionWaiters.delete(m.id);f(m.data||{});}}if(m.type==="reaction_request"){const data:any=m.data||{};if(data.targetId&&data.targetId===attacker?.item?.id&&data.requestedBy!==OBR.player.id&&Number(attacker?.data?.pilot?.reactions||0)>0)setPending(m);}});offItems=(OBR.scene.items as any).onChange?.(()=>{if(lockedId)void loadSensor();});});return()=>{offPlayer();offBroadcast();offItems();};},[lockedId,attacker?.item?.id]);
 useEffect(()=>{if(lockedId)void loadSensor();},[lockedId,attacker?.data?.sensor,attacker?.data?.sensorBonus]);
 useEffect(()=>{if(attacker?.data?.color==="#ffffff")void (async()=>{const c=await playerColor();if(c)saveRyder(attacker.item.id,{...attacker.data,color:c});})();},[attacker?.item?.id]);
 if(!ready)return <main><h2>PWB Ryder Combat</h2><p>Connecting to Owlbear Rodeo…</p></main>;
 if(error)return <main><h2>PWB Ryder Combat</h2><section><b>Extension error</b><p>{error}</p><button onClick={()=>void refreshAttacker()}>RETRY</button></section></main>;
 if(!attacker)return <main><h2>PWB Ryder Combat</h2><p>Select a Character token to operate or configure a Ryder.</p></main>;
 const{item}=attacker;const d:RyderData=attacker.data;
 const save=(patch:Partial<RyderData>)=>{const nd={...d,...patch};setAttacker({item,data:nd});void saveRyder(item.id,nd);};
 const savePilot=(patch:Partial<PilotData>)=>save({pilot:{...d.pilot,...patch}});
 const saveSkills=(patch:Partial<PilotData["skills"]>)=>savePilot({skills:{...d.pilot.skills,...patch}});
 const n=(k:keyof RyderData)=><Num value={Number(d[k])} onChange={v=>save({[k]:v} as any)}/>;
 const canOperate=async()=>{if(!d.ownerPlayerId)return true;return d.ownerPlayerId===myId||await isGM();};
 const claim=async()=>{if(d.ownerPlayerId&&d.ownerPlayerId!==myId&&!(await isGM())){localResult(`Ryder is claimed by ${d.ownerPlayerName||"another player"}.`,d.color);return;}if(d.ownerPlayerId===myId)save({ownerPlayerId:"",ownerPlayerName:""});else save({ownerPlayerId:myId,ownerPlayerName:myName});};
 const startTurn=async()=>{if(!(await canOperate()))return;const maxE=d.maxEnergy+d.energyBonus;const vent=d.heatVent+d.heatVentBonus+(d.pilot.skills.heatManagement*5);const heat=Math.max(0,d.heat-vent);const energy=Math.min(maxE,d.energy+maxE);const weapons=d.weapons.map(w=>w.ammo<=0?{...w,ammo:w.maxAmmo}:w);const reactions=Math.max(1,d.pilot.maxReactions);save({energy,heat,weapons,pilot:{...d.pilot,reactions,maxReactions:reactions}});await announce(`${d.name}: Turn started — Energy restored, ${vent} Heat vented, weapons reloaded where empty.`,d.color);};
 const addWeapon=()=>save({weapons:[...d.weapons,{id:crypto(),name:"New Weapon",ammo:10,maxAmmo:10,ammoCost:fixed(1),energyCost:fixed(0),heatCost:fixed(0),damage:"1d10",toHit:0,range:1200,fireRate:1,critical:20,effect:"",attackType:"ranged",status:"",soundUrl:"",traits:"",integrated:false,multi:1,scatter:1,damageType:"Piercing",reload:true,enabled:true}]});
 const updateW=(idx:number,p:Partial<Weapon>)=>save({weapons:d.weapons.map((w,i)=>i===idx?{...w,...p}:w)});
 const updateAction=(idx:number,p:Partial<ActionDef>)=>save({actions:d.actions.map((a,i)=>i===idx?{...a,...p}:a)});
 const updateReaction=(idx:number,p:Partial<ReactionDef>)=>save({reactions:d.reactions.map((r,i)=>i===idx?{...r,...p}:r)});
 const updateTalent=(idx:number,p:Partial<TalentDef>)=>savePilot({talents:d.pilot.talents.map((t,i)=>i===idx?{...t,...p}:t)});
 const selectedTargetFromMap=async()=>{const ids=await selectedIds();if(!ids?.length){localResult("Select a Character token as the target.",d.color);return null;}const all=await OBR.scene.items.getItems(ids);const t=all.find(x=>x.layer==="CHARACTER"&&x.id!==lockedId);if(!t){localResult("Select one Character token other than the locked attacker.",d.color);return null;}await chooseTarget(t.id);return await getRyderById(t.id);};
 const requestReaction=async(targetId:string,trigger:"before_attack"|"after_hit",attackTotal=0)=>{const id=crypto();const p=new Promise<any>(resolve=>{reactionWaiters.set(id,resolve);window.setTimeout(()=>{if(reactionWaiters.has(id)){reactionWaiters.delete(id);resolve(null);}},5000);});await OBR.broadcast.sendMessage(CHANNEL,{type:"reaction_request",id,data:{targetId,trigger,attackTotal,requestedBy:myId}},{destination:"ALL"});return p;};
 const resolveCounterattack=async(target:any,response:any)=>{if(!response?.counterattackWeaponId)return"";const wr=target.data.weapons.find((w:Weapon)=>w.id===response.counterattackWeaponId&&w.enabled);if(!wr)return"";const ec=costAmount(wr.energyCost,target.data.maxEnergy),hc=costAmount(wr.heatCost,target.data.heatCapacity),ac=costAmount(wr.ammoCost,wr.maxAmmo);if(wr.attackType!=="melee"&&!(await distanceBetween(target.item,item)<=wr.range))return"Counterattack failed: target out of range.";if(target.data.energy<ec||wr.ammo<ac)return"Counterattack unavailable: insufficient resources.";const atkRoll=wr.attackType==="melee"?target.data.pilot.skills.closeCombat:target.data.pilot.skills.sharpshooting;const rr=resolveAttack(wr.toHit+atkRoll+target.data.pilot.proficiencyBonus,d.evasion+d.evasionBonus,wr.damage,d.armor+d.armorBonus,d.cover,wr.critical,target.data.damageBonus,"normal");const damage=rr.finalDamage;const newHeat=target.data.heat+hc;const nw={...wr,ammo:Math.max(0,wr.ammo-ac)};const td={...target.data,energy:target.data.energy-ec,heat:newHeat,weapons:target.data.weapons.map((w:Weapon)=>w.id===wr.id?nw:w)};await saveRyder(target.item.id,td);await OBR.scene.items.updateItems([item.id],xs=>{for(const x of xs){const cur={...defaultRyder(),...((x.metadata?.["com.pwb.ryder-combat/data"] as RyderData)||{})};cur.hp=Math.max(0,cur.hp-damage);if(cur.hp<=0)cur.disabled=true;x.metadata["com.pwb.ryder-combat/data"]=cur;}});return`${target.data.name} counterattacks with ${wr.name}: ${rr.hit?`${damage} damage`:`miss`}.`;};
 const attack=async(w:Weapon)=>{if(!(await canOperate())){localResult("You do not own this Ryder.",d.color);return;}if(d.disabled||d.scrap){await announce(`${d.name}: ATTACK FAILED — Ryder is disabled or scrap.`,d.color);return;}const target=selectedTarget||await selectedTargetFromMap();if(!target)return;const distance=target.distance??await distanceBetween(item,target.item);const sensor=d.sensor+d.sensorBonus;if(distance>sensor){await announce(`${d.name}: ${w.name} — OUTSIDE SENSOR RANGE (${short(distance)} / ${short(sensor)} ft).`,d.color);return;}if(distance>w.range){await announce(`${d.name}: ${w.name} — OUT OF RANGE (${short(distance)} / ${short(w.range)} ft).`,d.color);return;}const ammoCost=costAmount(w.ammoCost,w.maxAmmo),energyCost=costAmount(w.energyCost,d.maxEnergy),heatCost=costAmount(w.heatCost,d.heatCapacity);const shots=Math.max(1,Math.floor(w.fireRate));if(w.ammo<ammoCost*shots){await announce(`${d.name}: ${w.name} — NOT ENOUGH AMMO.`,d.color);return;}if(d.energy<energyCost*shots){await announce(`${d.name}: ${w.name} — NOT ENOUGH ENERGY.`,d.color);return;}const hasPreReaction=target.data.reactions.some((r:ReactionDef)=>r.enabled&&r.trigger==="before_attack"); const pre=hasPreReaction?await requestReaction(target.item.id,"before_attack"):null;const preEvasion=Number(pre?.evasionBonus||0);let hits=0,crits=0,total=0,coverHits=0;const detail:string[]=[];let reduction=Number(pre?.damageReduction||0);for(let i=0;i<shots;i++){const mode:RollMode=pre?.advantage?"disadvantage":"normal";const skill=w.attackType==="melee"?d.pilot.skills.closeCombat:d.pilot.skills.sharpshooting;const r=resolveAttack(w.toHit+d.pilot.proficiencyBonus+skill+d.attackBonus,(target.data.evasion||0)+(target.data.evasionBonus||0)+preEvasion,w.damage,(target.data.armor||0)+(target.data.armorBonus||0),target.data.cover,w.critical,d.damageBonus,mode);let effective=r;if(r.hit&&!r.hitCover){const hasAfterReaction=target.data.reactions.some((x:ReactionDef)=>x.enabled&&x.trigger==="after_hit"); const after=hasAfterReaction?await requestReaction(target.item.id,"after_hit",r.total):null;if(after?.evasionSuccess){effective={...r,hit:false,finalDamage:0};}if(after?.damageReduction)reduction=Math.max(reduction,Number(after.damageReduction));if(after?.counterattackWeaponId){const ca=await resolveCounterattack(target,after);if(ca)await announce(ca,target.data.color);}}if(effective.hit)hits++;if(effective.critical)crits++;if(effective.hitCover)coverHits++;const dealt=Math.max(0,Math.floor(effective.finalDamage*(1-Math.max(0,Math.min(100,reduction))/100)));total+=dealt;detail.push(`d20 ${effective.roll}+${r.total-effective.roll}=${effective.total}${effective.critical?" CRIT":""}${effective.hitCover?" COVER":effective.hit?` ${dealt} dmg`:` MISS`}`);}
 const targetAfter={...target.data};targetAfter.hp=Math.max(0,targetAfter.hp-total);let structure="",overheat="";if(total>0&&targetAfter.hp<=0){structure=structureResult();if(structure==="Critical Damage")targetAfter.disabled=true;}if(crits>0){structure=structureResult();overheat=overheatResult();targetAfter.unstable=structure==="Critical Damage"||targetAfter.unstable;if(structure==="Critical Damage")targetAfter.disabled=true;if(overheat==="Reactor Meltdown")targetAfter.meltdown=true;if(overheat==="Reactor Overheat")targetAfter.energy=Math.floor((targetAfter.maxEnergy+targetAfter.energyBonus)/2);}if(w.status&&hits>0&&!targetAfter.statuses.includes(w.status))targetAfter.statuses=[...targetAfter.statuses,w.status];if((w.traits||"").toLowerCase().includes("concussion")&&total>0&&!targetAfter.statuses.includes("Staggered"))targetAfter.statuses=[...targetAfter.statuses,"Staggered"];await saveRyder(target.item.id,targetAfter);const newHeat=d.heat+heatCost*shots;let attackerOverheat="";let energy=Math.max(0,d.energy-energyCost*shots);if(newHeat>d.heatCapacity+d.heatCapacityBonus){attackerOverheat=overheatResult();if(attackerOverheat==="Reactor Overheat")energy=Math.floor((d.maxEnergy+d.energyBonus)/2);if(attackerOverheat==="Reactor Meltdown")save({meltdown:true});}const nw={...w,ammo:Math.max(0,w.ammo-ammoCost*shots)};save({energy,heat:newHeat,weapons:d.weapons.map(x=>x.id===w.id?nw:x)});playSound(w.soundUrl);let extra="";if(structure)extra+=` Structure: ${structure}.`;if(overheat)extra+=` Target ${overheat}.`;if(attackerOverheat)extra+=` Attacker ${attackerOverheat}.`;if(w.status&&hits>0)extra+=` Status: ${w.status}.`;if(reduction)extra+=` Reaction reduced damage by ${reduction}%.`;const text=`${d.name} fires ${w.name} at ${target.data.name} — ${hits}/${shots} hits, ${crits} critical, ${coverHits} cover, ${total} damage.${extra}`;await announce(text,d.color);setMessage(text);setSelectedTarget({...target,data:targetAfter,distance});setTab("weapons");setMessage(detail.join(" | "));};
 const useAction=async(a:ActionDef)=>{if(!(await canOperate()))return;const ec=costAmount(a.energyCost,d.maxEnergy),hc=costAmount(a.heatCost,d.heatCapacity);if(d.energy<ec){await announce(`${d.name}: ${a.name} — NOT ENOUGH ENERGY.`,d.color);return;}const heat=d.heat+hc;save({energy:d.energy-ec,heat});playSound(a.soundUrl);let oh="";if(heat>d.heatCapacity+d.heatCapacityBonus){oh=overheatResult();if(oh==="Reactor Overheat")save({energy:Math.floor((d.maxEnergy+d.energyBonus)/2)});if(oh==="Reactor Meltdown")save({meltdown:true});}await announce(`${d.name} activates ${a.name}.${a.effect?` ${a.effect}`:""}${oh?` ${oh}.`:""}`,d.color);};
 const addAction=()=>save({actions:[...d.actions,{id:crypto(),name:"New Action",energyCost:fixed(0),heatCost:fixed(0),effect:"",soundUrl:"",enabled:true}]});
 const addReaction=()=>save({reactions:[...d.reactions,{id:crypto(),name:"New Reaction",trigger:"after_hit",energyCost:fixed(0),heatCost:fixed(0),evasionBonus:0,damageReduction:0,counterattack:false,counterattackWeaponId:"",effect:"",enabled:true}]});
 const addTalent=()=>savePilot({talents:[...d.pilot.talents,{id:crypto(),name:"New Talent",description:"",energyCost:fixed(0),heatCost:fixed(0),kiCost:0,effect:"",enabled:true}]});
 const useTalent=async(t:TalentDef)=>{if(!(await canOperate()))return;const ec=costAmount(t.energyCost,d.maxEnergy),hc=costAmount(t.heatCost,d.heatCapacity);if(d.energy<ec){await announce(`${d.name}: ${t.name} — NOT ENOUGH ENERGY.`,d.color);return;}if(d.pilot.kiDice<t.kiCost){await announce(`${d.name}: ${t.name} — NOT ENOUGH KI.`,d.color);return;}let heat=d.heat+hc;let oh="";if(heat>d.heatCapacity+d.heatCapacityBonus){oh=overheatResult();}save({energy:d.energy-ec,heat,pilot:{...d.pilot,kiDice:d.pilot.kiDice-t.kiCost}});playSound("");await announce(`${d.name} activates talent ${t.name}.${t.effect?` ${t.effect}`:""}${oh?` ${oh}.`:""}`,d.color);};
 const lock=async()=>{if(lockedId){setLockedId("");setSelectedTarget(null);await announce(`${d.name}: attacker unlocked.`,d.color);return;}const selected=await getSelectedRyder();if(!selected){localResult("Select a Character token first.",d.color);return;}setAttacker(selected);setLockedId(selected.item.id);setSelectedTarget(null);await announce(`${selected.data.name}: attacker locked.`,selected.data.color);};
 const release=async()=>{if(!d.ownerPlayerId||d.ownerPlayerId===myId||await isGM())save({ownerPlayerId:"",ownerPlayerName:""});};
 const rollStructure=async()=>{const r=structureResult();await announce(`${d.name}: Structure Damage Check — ${r}.`,d.color);};
 const rollOverheat=async()=>{const r=overheatResult();if(r==="Reactor Overheat")save({energy:Math.floor((d.maxEnergy+d.energyBonus)/2)});if(r==="Reactor Meltdown")save({meltdown:true});await announce(`${d.name}: Overheating Check — ${r}.`,d.color);};
 const pilot=d.pilot;
 const tabs=["stats","weapons","actions","reactions","sensor","pilot","systems","log"];
 return <main>
  <header style={{borderLeft:`5px solid ${d.color}`}}><h2>{d.name||item.name||"Ryder"}</h2><small>{d.ownerPlayerId?`Claimed by ${d.ownerPlayerName}`:"Unclaimed"}{lockedId?" • ATTACKER LOCKED":""}</small></header>
  <section><label>Ryder Name<input value={d.name} onChange={e=>save({name:e.target.value})}/></label><label>Ryder Color<input type="color" value={d.color} onChange={e=>save({color:e.target.value})}/></label><div className="row"><button onClick={()=>void claim()}>{d.ownerPlayerId===myId?"RELEASE OWNERSHIP":"CLAIM OWNERSHIP"}</button><button onClick={()=>void release()}>GM RELEASE</button><button onClick={()=>void lock()}>{lockedId?"UNLOCK ATTACKER":"LOCK SELECTED"}</button></div></section>
  <nav>{tabs.map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</nav>
  {tab==="stats"&&<><section><h3>Ryder</h3><div className="grid">{[["HP","hp"],["Max HP","maxHp"],["Armor","armor"],["Energy","energy"],["Max Energy","maxEnergy"],["Heat","heat"],["Heat Capacity","heatCapacity"],["Heat Vent","heatVent"],["Evasion","evasion"],["Sensor","sensor"],["Move Speed","moveSpeed"],["Frame","frame"],["Speed","speed"],["System","system"],["Engineering","engineering"]].map(([l,k])=><label key={k}>{l}{n(k as keyof RyderData)}</label>)}</div></section><section><h3>Turn</h3><button className="primary" onClick={()=>void startTurn()}>START TURN / RELOAD</button><p>Energy fully restores at the start of the turn. Heat vents by Heat Vent + Heat Management ×5.</p><label>Cover<select value={d.cover} onChange={e=>save({cover:e.target.value as Cover})}><option value="none">None</option><option value="light">Light</option><option value="medium">Half Cover</option><option value="hard">Three-Quarter Cover</option><option value="full">Full Cover</option></select></label><p>Status: {d.statuses.length?d.statuses.join(", "):"None"}</p></section></>}
  {tab==="weapons"&&<section><h3>Weapons</h3><button onClick={addWeapon}>+ Weapon</button>{d.weapons.map((w,i)=><article key={w.id}><input className="wide" value={w.name} onChange={e=>updateW(i,{name:e.target.value})}/><div className="grid"><label>Ammo<Num value={w.ammo} onChange={v=>updateW(i,{ammo:v})}/></label><label>Max Ammo<Num value={w.maxAmmo} onChange={v=>updateW(i,{maxAmmo:v})}/></label><label>Ammo Cost<CostEditor cost={w.ammoCost} onChange={v=>updateW(i,{ammoCost:v})}/></label><label>Energy Cost<CostEditor cost={w.energyCost} onChange={v=>updateW(i,{energyCost:v})}/></label><label>Heat Cost<CostEditor cost={w.heatCost} onChange={v=>updateW(i,{heatCost:v})}/></label><label>Range<Num value={w.range} onChange={v=>updateW(i,{range:v})}/></label><label>Fire Rate<Num value={w.fireRate} onChange={v=>updateW(i,{fireRate:v})}/></label><label>Critical<Num value={w.critical} onChange={v=>updateW(i,{critical:v})}/></label><label>To Hit<Num value={w.toHit} onChange={v=>updateW(i,{toHit:v})}/></label><label>Multi<Num value={w.multi} onChange={v=>updateW(i,{multi:v})}/></label><label>Scatter<Num value={w.scatter} onChange={v=>updateW(i,{scatter:v})}/></label></div><label>Type<select value={w.attackType} onChange={e=>updateW(i,{attackType:e.target.value as any})}><option value="ranged">Ranged</option><option value="melee">Melee</option><option value="force">Force</option></select></label><label>Damage<input value={w.damage} onChange={e=>updateW(i,{damage:e.target.value})}/></label><label>Damage Type<input value={w.damageType} onChange={e=>updateW(i,{damageType:e.target.value})}/></label><label>Traits<input value={w.traits} onChange={e=>updateW(i,{traits:e.target.value})}/></label><label>Status on Hit<input value={w.status} onChange={e=>updateW(i,{status:e.target.value})}/></label><label>Sound URL<input value={w.soundUrl} onChange={e=>updateW(i,{soundUrl:e.target.value})}/></label><textarea value={w.effect} onChange={e=>updateW(i,{effect:e.target.value})}/><button className="primary" onClick={()=>void attack(w)}>ATTACK SELECTED TARGET</button></article>)}</section>}
  {tab==="actions"&&<section><button onClick={addAction}>+ Action</button>{d.actions.map((a,i)=><article key={a.id}><input className="wide" value={a.name} onChange={e=>updateAction(i,{name:e.target.value})}/><label>Energy Cost<CostEditor cost={a.energyCost} onChange={v=>updateAction(i,{energyCost:v})}/></label><label>Heat Cost<CostEditor cost={a.heatCost} onChange={v=>updateAction(i,{heatCost:v})}/></label><label>Sound URL<input value={a.soundUrl} onChange={e=>updateAction(i,{soundUrl:e.target.value})}/></label><textarea value={a.effect} onChange={e=>updateAction(i,{effect:e.target.value})}/><button onClick={()=>void useAction(a)}>USE ACTION</button></article>)}</section>}
  {tab==="reactions"&&<section><p>Reactions are resolved against the triggering attack and can add Evasion, reduce damage, or make a counterattack.</p>{d.reactions.map((r,i)=><article key={r.id}><input className="wide" value={r.name} onChange={e=>updateReaction(i,{name:e.target.value})}/><label>Trigger<select value={r.trigger} onChange={e=>updateReaction(i,{trigger:e.target.value as any})}><option value="before_attack">Before Attack</option><option value="after_hit">After Hit</option></select></label><label>Energy Cost<CostEditor cost={r.energyCost} onChange={v=>updateReaction(i,{energyCost:v})}/></label><label>Heat Cost<CostEditor cost={r.heatCost} onChange={v=>updateReaction(i,{heatCost:v})}/></label><label>Evasion Bonus<Num value={r.evasionBonus} onChange={v=>updateReaction(i,{evasionBonus:v})}/></label><label>Damage Reduction %<Num value={r.damageReduction} onChange={v=>updateReaction(i,{damageReduction:v})}/></label><label>Counterattack<input type="checkbox" checked={r.counterattack} onChange={e=>updateReaction(i,{counterattack:e.target.checked})}/></label><label>Counterattack Weapon<select value={r.counterattackWeaponId} onChange={e=>updateReaction(i,{counterattackWeaponId:e.target.value})}><option value="">None</option>{d.weapons.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><textarea value={r.effect} onChange={e=>updateReaction(i,{effect:e.target.value})}/></article>)}<button onClick={addReaction}>+ Reaction</button>{pending&&<section className="reaction"><b>INCOMING ATTACK — REACTION</b><p>Choose a prepared reaction for the incoming attack.</p>{d.reactions.filter(r=>r.enabled&&r.trigger===(pending.data as any)?.trigger).map(r=><button key={r.id} className="primary" onClick={()=>{const ec=costAmount(r.energyCost,d.maxEnergy),hc=costAmount(r.heatCost,d.heatCapacity);if(d.energy<ec){localResult("NOT ENOUGH ENERGY FOR REACTION.",d.color);return;}const reqData:any=pending.data||{}; const evasionRoll=Number(reqData.attackTotal||0)>0 ? rollDie(20)+d.speed+d.pilot.skills.reflex+r.evasionBonus : 0; const payload={evasionBonus:r.evasionBonus,damageReduction:r.damageReduction,counterattackWeaponId:r.counterattack?r.counterattackWeaponId:"",evasionRoll,evasionSuccess:r.trigger==="after_hit"&&evasionRoll>Number(reqData.attackTotal||0)};save({energy:d.energy-ec,heat:d.heat+hc,pilot:{...d.pilot,reactions:Math.max(0,d.pilot.reactions-1)}});void OBR.broadcast.sendMessage(CHANNEL,{type:"reaction_response",id:pending.id,data:payload},{destination:"ALL"});setPending(null);}}>{r.name}</button>)}<button onClick={()=>{const p=pending;setPending(null);void OBR.broadcast.sendMessage(CHANNEL,{type:"reaction_response",id:p.id,data:{}},{destination:"ALL"});}}>DECLINE</button></section>}</section>}
  {tab==="sensor"&&<section><h3>Sensor</h3><p>Sensor Range: {short(d.sensor+d.sensorBonus)} ft</p><button onClick={()=>void loadSensor()}>REFRESH DETECTION</button>{sensorTargets.length===0?<p>No detected targets.</p>:<div>{sensorTargets.map(r=><article key={r.item.id}><b>{r.data.name||r.item.name||"Unknown Contact"}</b><span> {short(r.distance)} ft</span><small>{r.data.team&&` • ${r.data.team}`}</small><button className="primary" onClick={()=>void chooseTarget(r.item.id)}>TARGET</button></article>)}</div>}{selectedTarget&&<p className="selected">Target: {selectedTarget.data.name} — {short(selectedTarget.distance)} ft</p>}</section>}
  {tab==="pilot"&&<section><h3>Pilot</h3><div className="grid"><label>Level<Num value={pilot.level} onChange={v=>savePilot({level:v})}/></label><label>Proficiency<Num value={pilot.proficiencyBonus} onChange={v=>savePilot({proficiencyBonus:v})}/></label><label>Ki Dice<Num value={pilot.kiDice} onChange={v=>savePilot({kiDice:v})}/></label><label>Max Ki<Num value={pilot.maxKiDice} onChange={v=>savePilot({maxKiDice:v})}/></label><label>Reactions<Num value={pilot.reactions} onChange={v=>savePilot({reactions:v})}/></label><label>Max Reactions<Num value={pilot.maxReactions} onChange={v=>savePilot({maxReactions:v})}/></label></div><h3>Skills</h3>{([['Sharpshooting','sharpshooting'],['Close Combat','closeCombat'],['Advanced Maneuver','advancedManeuver'],['Reflex','reflex'],['Electronic Warfare','electronicWarfare'],['System Analysis','systemAnalysis'],['Heat Management','heatManagement'],['Maintenance','maintenance']] as const).map(([l,k])=><label key={k}>{l}<Num value={pilot.skills[k]} onChange={v=>saveSkills({[k]:v})}/></label>)}<h3>Talents</h3><button onClick={addTalent}>+ Talent</button>{pilot.talents.map((t,i)=><article key={t.id}><input className="wide" value={t.name} onChange={e=>updateTalent(i,{name:e.target.value})}/><textarea value={t.description} onChange={e=>updateTalent(i,{description:e.target.value})}/><label>Energy Cost<CostEditor cost={t.energyCost} onChange={v=>updateTalent(i,{energyCost:v})}/></label><label>Heat Cost<CostEditor cost={t.heatCost} onChange={v=>updateTalent(i,{heatCost:v})}/></label><label>Ki Cost<Num value={t.kiCost} onChange={v=>updateTalent(i,{kiCost:v})}/></label><textarea value={t.effect} onChange={e=>updateTalent(i,{effect:e.target.value})}/><button className="primary" onClick={()=>void useTalent(t)}>ACTIVATE TALENT</button></article>)}</section>}
  {tab==="systems"&&<section><h3>Checks</h3><button onClick={()=>void rollStructure()}>STRUCTURE DAMAGE CHECK</button><button onClick={()=>void rollOverheat()}>OVERHEATING CHECK</button><p>Disabled: {String(d.disabled)} • Meltdown: {String(d.meltdown)} • Unstable: {String(d.unstable)} • Scrap: {String(d.scrap)}</p><h3>Tech</h3><p>Tech Attack bonus: {d.techAttackBonus}. System Analysis 1/2/4/6/8/10 reveals progressively deeper information, up to complete Ryder information.</p></section>}
  {tab==="log"&&<section><h3>Combat Log</h3>{log.length?log.map((x,i)=><p key={i} className="log" style={{borderLeftColor:x.color||"#777"}}>{x.text}</p>):<p>No combat results yet.</p>}</section>}
  {message&&<p className="msg" style={{borderColor:d.color}}>{message}</p>}
 </main>;
}
createRoot(document.getElementById("root")!).render(<App/>);
