import type {Cover,ResourceCost,RollMode} from "./types";
export function rollDie(sides:number){return Math.floor(Math.random()*sides)+1;}
export function rollD20(mode:RollMode="normal"){const a=rollDie(20);if(mode==="normal")return a;const b=rollDie(20);return mode==="advantage"?Math.max(a,b):Math.min(a,b);}
export function rollExpression(expr:string){const m=expr.trim().replace(/\s+/g,"").match(/^(\d*)d(\d+)([+-]\d+)?$/i);if(!m)return Number(expr)||0;const count=Number(m[1]||1),sides=Number(m[2]),mod=Number(m[3]||0);let total=mod;for(let i=0;i<count;i++)total+=rollDie(sides);return total;}
export function costAmount(cost:ResourceCost,max:number){return cost.mode==="percent"?Math.ceil(max*cost.value/100):Math.max(0,cost.value);}
export function coverResult(cover:Cover){if(cover==="none")return{hitsCover:false,roll:0};if(cover==="full")return{hitsCover:true,roll:0};const r=rollDie(4);if(cover==="light")return{hitsCover:r===1,roll:r};if(cover==="medium")return{hitsCover:r<=2,roll:r};return{hitsCover:r<=3,roll:r};}
export interface AttackResult{roll:number;total:number;hit:boolean;critical:boolean;coverRoll:number;hitCover:boolean;damage:number;finalDamage:number;}
export function resolveAttack(toHit:number,targetEvasion:number,damageExpr:string,armor:number,cover:Cover,critical:number,damageBonus=0,mode:RollMode="normal",damageReduction=0):AttackResult{const roll=rollD20(mode),total=roll+toHit,hit=roll===20||total>=targetEvasion;if(!hit)return{roll,total,hit:false,critical:false,coverRoll:0,hitCover:false,damage:0,finalDamage:0};const cr=coverResult(cover);if(cr.hitsCover)return{roll,total,hit:true,critical:roll>=critical,coverRoll:cr.roll,hitCover:true,damage:0,finalDamage:0};const damage=rollExpression(damageExpr)+damageBonus;const finalDamage=Math.max(0,damage-armor-damageReduction);return{roll,total,hit:true,critical:roll>=critical,coverRoll:cr.roll,hitCover:false,damage,finalDamage};}
export function structureResult(){const r=rollDie(6);if(r>=5)return"Minor Damage";if(r>=2)return"Major Damage";return"Critical Damage";}
export function overheatResult(){const r=rollDie(6);if(r===1)return"Reactor Meltdown";if(r<=4)return"Reactor Overheat";return"Reactor Stress";}
